// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: messageDefine.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReqInfoBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ver         *int32 `protobuf:"varint,1,opt,name=ver,proto3,oneof" json:"ver,omitempty"`
	MessageType *int32 `protobuf:"varint,2,opt,name=message_type,json=messageType,proto3,oneof" json:"message_type,omitempty"`
}

func (x *ReqInfoBase) Reset() {
	*x = ReqInfoBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messageDefine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqInfoBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqInfoBase) ProtoMessage() {}

func (x *ReqInfoBase) ProtoReflect() protoreflect.Message {
	mi := &file_messageDefine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqInfoBase.ProtoReflect.Descriptor instead.
func (*ReqInfoBase) Descriptor() ([]byte, []int) {
	return file_messageDefine_proto_rawDescGZIP(), []int{0}
}

func (x *ReqInfoBase) GetVer() int32 {
	if x != nil && x.Ver != nil {
		return *x.Ver
	}
	return 0
}

func (x *ReqInfoBase) GetMessageType() int32 {
	if x != nil && x.MessageType != nil {
		return *x.MessageType
	}
	return 0
}

type RspInfoBase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ver         *int32 `protobuf:"varint,1,opt,name=ver,proto3,oneof" json:"ver,omitempty"`
	MessageType *int32 `protobuf:"varint,2,opt,name=message_type,json=messageType,proto3,oneof" json:"message_type,omitempty"`
}

func (x *RspInfoBase) Reset() {
	*x = RspInfoBase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messageDefine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RspInfoBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RspInfoBase) ProtoMessage() {}

func (x *RspInfoBase) ProtoReflect() protoreflect.Message {
	mi := &file_messageDefine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RspInfoBase.ProtoReflect.Descriptor instead.
func (*RspInfoBase) Descriptor() ([]byte, []int) {
	return file_messageDefine_proto_rawDescGZIP(), []int{1}
}

func (x *RspInfoBase) GetVer() int32 {
	if x != nil && x.Ver != nil {
		return *x.Ver
	}
	return 0
}

func (x *RspInfoBase) GetMessageType() int32 {
	if x != nil && x.MessageType != nil {
		return *x.MessageType
	}
	return 0
}

type VoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ver         *int32  `protobuf:"varint,1,opt,name=ver,proto3,oneof" json:"ver,omitempty"`
	Term        *uint64 `protobuf:"varint,2,opt,name=term,proto3,oneof" json:"term,omitempty"`
	CandidateId *string `protobuf:"bytes,3,opt,name=candidateId,proto3,oneof" json:"candidateId,omitempty"`
	LastLogIdx  *uint64 `protobuf:"varint,4,opt,name=lastLogIdx,proto3,oneof" json:"lastLogIdx,omitempty"`
	LastLogTerm *uint64 `protobuf:"varint,5,opt,name=lastLogTerm,proto3,oneof" json:"lastLogTerm,omitempty"`
}

func (x *VoteRequest) Reset() {
	*x = VoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messageDefine_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequest) ProtoMessage() {}

func (x *VoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messageDefine_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequest.ProtoReflect.Descriptor instead.
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return file_messageDefine_proto_rawDescGZIP(), []int{2}
}

func (x *VoteRequest) GetVer() int32 {
	if x != nil && x.Ver != nil {
		return *x.Ver
	}
	return 0
}

func (x *VoteRequest) GetTerm() uint64 {
	if x != nil && x.Term != nil {
		return *x.Term
	}
	return 0
}

func (x *VoteRequest) GetCandidateId() string {
	if x != nil && x.CandidateId != nil {
		return *x.CandidateId
	}
	return ""
}

func (x *VoteRequest) GetLastLogIdx() uint64 {
	if x != nil && x.LastLogIdx != nil {
		return *x.LastLogIdx
	}
	return 0
}

func (x *VoteRequest) GetLastLogTerm() uint64 {
	if x != nil && x.LastLogTerm != nil {
		return *x.LastLogTerm
	}
	return 0
}

type VoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ver         *int32 `protobuf:"varint,1,opt,name=ver,proto3,oneof" json:"ver,omitempty"`
	Term        uint64 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted bool   `protobuf:"varint,3,opt,name=voteGranted,proto3" json:"voteGranted,omitempty"`
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messageDefine_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messageDefine_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_messageDefine_proto_rawDescGZIP(), []int{3}
}

func (x *VoteResponse) GetVer() int32 {
	if x != nil && x.Ver != nil {
		return *x.Ver
	}
	return 0
}

func (x *VoteResponse) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *VoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

var File_messageDefine_proto protoreflect.FileDescriptor

var file_messageDefine_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x61, 0x66, 0x74, 0x6c, 0x69, 0x62, 0x22, 0x65,
	0x0a, 0x0b, 0x72, 0x65, 0x71, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x61, 0x73, 0x65, 0x12, 0x15, 0x0a,
	0x03, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x03, 0x76, 0x65,
	0x72, 0x88, 0x01, 0x01, 0x12, 0x26, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x0b, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04,
	0x5f, 0x76, 0x65, 0x72, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0x65, 0x0a, 0x0b, 0x72, 0x73, 0x70, 0x49, 0x6e, 0x66, 0x6f,
	0x42, 0x61, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x03, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x00, 0x52, 0x03, 0x76, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x26, 0x0a, 0x0c, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x01, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x76, 0x65, 0x72, 0x42, 0x0f, 0x0a, 0x0d, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x22, 0xf0, 0x01, 0x0a,
	0x0b, 0x76, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x03,
	0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x03, 0x76, 0x65, 0x72,
	0x88, 0x01, 0x01, 0x12, 0x17, 0x0a, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x48, 0x01, 0x52, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b,
	0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x02, 0x52, 0x0b, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x49, 0x64,
	0x88, 0x01, 0x01, 0x12, 0x23, 0x0a, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x49, 0x64,
	0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x48, 0x03, 0x52, 0x0a, 0x6c, 0x61, 0x73, 0x74, 0x4c,
	0x6f, 0x67, 0x49, 0x64, 0x78, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x6c, 0x61, 0x73, 0x74,
	0x4c, 0x6f, 0x67, 0x54, 0x65, 0x72, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x48, 0x04, 0x52,
	0x0b, 0x6c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x54, 0x65, 0x72, 0x6d, 0x88, 0x01, 0x01, 0x42,
	0x06, 0x0a, 0x04, 0x5f, 0x76, 0x65, 0x72, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x74, 0x65, 0x72, 0x6d,
	0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x63, 0x61, 0x6e, 0x64, 0x69, 0x64, 0x61, 0x74, 0x65, 0x49, 0x64,
	0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x49, 0x64, 0x78, 0x42,
	0x0e, 0x0a, 0x0c, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x54, 0x65, 0x72, 0x6d, 0x22,
	0x63, 0x0a, 0x0c, 0x76, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x15, 0x0a, 0x03, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x03,
	0x76, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x76, 0x6f,
	0x74, 0x65, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0b, 0x76, 0x6f, 0x74, 0x65, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x42, 0x06, 0x0a, 0x04,
	0x5f, 0x76, 0x65, 0x72, 0x32, 0x47, 0x0a, 0x0a, 0x52, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x39, 0x0a, 0x07, 0x72, 0x70, 0x63, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x14, 0x2e,
	0x72, 0x61, 0x66, 0x74, 0x6c, 0x69, 0x62, 0x2e, 0x72, 0x65, 0x71, 0x49, 0x6e, 0x66, 0x6f, 0x42,
	0x61, 0x73, 0x65, 0x1a, 0x14, 0x2e, 0x72, 0x61, 0x66, 0x74, 0x6c, 0x69, 0x62, 0x2e, 0x72, 0x73,
	0x70, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x61, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messageDefine_proto_rawDescOnce sync.Once
	file_messageDefine_proto_rawDescData = file_messageDefine_proto_rawDesc
)

func file_messageDefine_proto_rawDescGZIP() []byte {
	file_messageDefine_proto_rawDescOnce.Do(func() {
		file_messageDefine_proto_rawDescData = protoimpl.X.CompressGZIP(file_messageDefine_proto_rawDescData)
	})
	return file_messageDefine_proto_rawDescData
}

var file_messageDefine_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_messageDefine_proto_goTypes = []interface{}{
	(*ReqInfoBase)(nil),  // 0: raftlib.reqInfoBase
	(*RspInfoBase)(nil),  // 1: raftlib.rspInfoBase
	(*VoteRequest)(nil),  // 2: raftlib.voteRequest
	(*VoteResponse)(nil), // 3: raftlib.voteResponse
}
var file_messageDefine_proto_depIdxs = []int32{
	0, // 0: raftlib.RpcService.rpcCall:input_type -> raftlib.reqInfoBase
	1, // 1: raftlib.RpcService.rpcCall:output_type -> raftlib.rspInfoBase
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_messageDefine_proto_init() }
func file_messageDefine_proto_init() {
	if File_messageDefine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messageDefine_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqInfoBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messageDefine_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RspInfoBase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messageDefine_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messageDefine_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_messageDefine_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_messageDefine_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_messageDefine_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_messageDefine_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messageDefine_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messageDefine_proto_goTypes,
		DependencyIndexes: file_messageDefine_proto_depIdxs,
		MessageInfos:      file_messageDefine_proto_msgTypes,
	}.Build()
	File_messageDefine_proto = out.File
	file_messageDefine_proto_rawDesc = nil
	file_messageDefine_proto_goTypes = nil
	file_messageDefine_proto_depIdxs = nil
}
